adjectives = adjectives.concat([
    'short',
    'crafty',
    'wiley',
    'sly',
    'cunning',
    'clever',
    'shrewd',
    'astute',
    'sharp',
    'smart',
    'ingenious',
    'resourceful',
    'quick-witted',
    'perspicacious',
    'discerning',
    'perceptive',
]);
